###
@ZenXKanAPI_HostAddress = http://localhost:5131

GET {{ZenXKanAPI_HostAddress}}/api/v1/Projects
Accept: application/json

###
GET {{ZenXKanAPI_HostAddress}}/api/v1/Projects/01J3KMTPRPG93W229D4DFB6J7E
Accept: application/json

###
POST {{ZenXKanAPI_HostAddress}}/api/v1/Projects
Content-Type: application/json

{
  "title": "Project 1"
}
