###
@ZenXKanAPI_HostAddress = http://localhost:5131

GET {{ZenXKanAPI_HostAddress}}/api/v1/tags
Accept: application/json

###
GET {{ZenXKanAPI_HostAddress}}/api/v1/tags/0245dc1e-6c34-4c1d-b9ae-bd3b20a55785
Accept: application/json

###
POST {{ZenXKanAPI_HostAddress}}/api/v1/tags
Content-Type: application/json

{
  "Name": "Tag 2",
  "Color": "yellow"
}

###
DELETE {{ZenXKanAPI_HostAddress}}/api/v1/tags/0245dc1e-6c34-4c1d-b9ae-bd3b20a55785
Accept: application/json
